# Generated by Django 4.1.7 on 2023-03-01 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RngBaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_number', models.IntegerField(default=0, verbose_name='Лицевой счёт')),
                ('account_balance', models.FloatField(default=0, null=True, verbose_name='Баланс лицевого счёта')),
                ('service_type_code', models.IntegerField(default=0, verbose_name='Тип услуги')),
                ('meter', models.BooleanField(default=0, verbose_name='Наличие счётчика')),
                ('meter_readings', models.IntegerField(default=0, verbose_name='Показания счётчика')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_type_name', models.CharField(default='', max_length=254)),
                ('services_type_code', models.IntegerField(default=0, unique=True)),
                ('services_type_rngcode', models.CharField(default='', max_length=9, unique=True)),
                ('services_type_priority', models.IntegerField(default=0, unique=True)),
            ],
        ),
    ]
