# Generated by Django 4.1.7 on 2023-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rng_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rngbaserecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='services_type_code',
            field=models.IntegerField(default=0, unique=True, verbose_name='Внутренний код услуги'),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='services_type_name',
            field=models.CharField(default='', max_length=254, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='services_type_priority',
            field=models.IntegerField(default=0, unique=True, verbose_name='Приоритет списания'),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='services_type_rngcode',
            field=models.CharField(default='', max_length=9, unique=True, verbose_name='Код услуги в РНГ'),
        ),
    ]
