# Generated by Django 4.1.7 on 2023-03-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rng_base', '0003_rename_services_type_code_servicestype_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rngbaserecord',
            options={'verbose_name': 'Запись в базе РНГ', 'verbose_name_plural': 'Записи в базе РНГ'},
        ),
        migrations.AlterModelOptions(
            name='servicestype',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
    ]
