version: '3.8'

services:
  web:
    restart: always
    # Берем Dockerfile из каталога app
    build: ./mrgServices
    # Открываем порт 8000 внутри и снаружи
    volumes:
      - ./files:/app/files
      - ./reestrs:/app/reestrs
      # - assistant_data:/app/import
      # - type: volume
      #   source: assistant_data
      #   target: /app/importfiles
      #   volume:
      #     nocopy: true
    environment:
      - REDIS_HOST=redis
    ports:
      - 8010:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
  db:
    restart: always
    hostname: db
    #command: sh -c "chmod 700 -R /var/lib/postgresql/data"
    # Образ и версия базы, которую мы будем использовать
    image: postgres:14
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - 6379:6379
  celery:
    build: ./mrgServices
    command: sh -c 'celery -A main worker --loglevel=info --concurrency=5 --pool=eventlet'
    env_file:
      - ./.env.dev
    volumes:
      - ./files:/app/files
      - ./reestrs:/app/reestrs
    depends_on:
      - web
      - db
      - redis
  celery-beat:
    build: ./mrgServices
    command: sh -c 'celery -A main beat -l debug'
    # volumes:
    #   - ./project/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
      - celery
  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5566']
    ports:
      - 5566:5566
    depends_on:
      - web
      - db
      - redis
      - celery
      - celery-beat
volumes:
  db:
  files:
  reestrs:
  # assistant_data:
  #   driver: local
  #   driver_opts:
  #     type: cifs
  #     # device: "\\\\172.17.156.10\\Obmen\\"
  #     # o: "username=U5630305,password=95486,domain=AC,vers=3.0,uid=4674,gid=S-1-5-21-3008397267-4057616034-1962435636"
  #     device: "//172.17.156.10/Obmen/"
  #     # o: "uid=4674, username=AC/U5630305, password=95486, iocharset=utf8, file_mode=0777, dir_mode=0777"
  #     # o: "username=U5630305, domain=AC, password=95486, uid=4674, gid-1000, vers=3.0, rw"
  #     o: "username=U5630305, password=95486, file_mode=0777,dir_mode=0777,uid=4674,gid=S-1-5-21-3008397267-4057616034-1962435636,vers=3.0, rw"
  #     # device: "//172.17.156.10/Obmen"