# Generated by Django 4.1.7 on 2023-10-23 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractVdgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_number', models.CharField(default='', max_length=8, null=True, verbose_name='Лицевой счёт (8)')),
                ('account_number_rng', models.CharField(default='', max_length=12, null=True, verbose_name='Лицевой счёт (12)')),
                ('account_address', models.CharField(default='', max_length=1024, verbose_name='Адрес установки борудования')),
            ],
            options={
                'verbose_name': 'Договор ВДГО',
                'verbose_name_plural': 'Договоры на обслуживание ВДГО',
            },
        ),
    ]
