# Generated by Django 4.1.7 on 2023-10-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractvdgo_passport_address_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='passport_scan_first',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='passport_scan_second',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
