# Generated by Django 4.1.7 on 2023-10-25 08:05

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractvdgo_passport_scan_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_first',
            field=models.ImageField(default=None, upload_to=contracts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_second',
            field=models.ImageField(default=None, upload_to=contracts.models.upload_to),
        ),
    ]
