# Generated by Django 4.1.7 on 2023-10-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contractvdgo_passport_scan_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_first',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_second',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
