# Generated by Django 4.1.7 on 2023-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contractvdgo_passport_scan_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='account_address',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Адрес установки борудования'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_address_registration',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_birth_date',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_issued',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_issued_code',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_issued_date',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_name',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='ФИО владельца договора'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_number',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_place',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_serial',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='Серия паспорта'),
        ),
    ]
