# Generated by Django 4.1.7 on 2023-10-26 21:31

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contractvdgo_account_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='consent',
            field=models.BooleanField(default=False, max_length=14, verbose_name='Подтверждение корректности данных'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='email',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Емайл'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='inn_first',
            field=models.ImageField(blank=True, default='', upload_to=contracts.models.upload_to, verbose_name='Лицевая сторона ИНН'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='inn_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Номер ИНН'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='is_sended',
            field=models.BooleanField(default=False, max_length=14, verbose_name='Отправлено в реестр'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='snils_first',
            field=models.ImageField(blank=True, default='', upload_to=contracts.models.upload_to, verbose_name='Лицевая сторона снилс'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='snils_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Номер снилс'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='account_address',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес установки борудования'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Лицевой счёт (8)'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='account_number_rng',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Лицевой счёт (12)'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_address_registration',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_birth_date',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_issued',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_issued_code',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_issued_date',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='ФИО владельца договора'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_place',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_first',
            field=models.ImageField(blank=True, default=None, upload_to=contracts.models.upload_to, verbose_name='Второй разворот паспорта'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_second',
            field=models.ImageField(blank=True, default=None, upload_to=contracts.models.upload_to, verbose_name='Страница паспорта с регистрацией'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_serial',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
    ]
