# Generated by Django 4.1.7 on 2023-10-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractvdgo_certificate_fifth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Телефон'),
        ),
    ]
