# Generated by Django 4.1.7 on 2023-10-28 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contractvdgo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='last_update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
