# Generated by Django 4.1.7 on 2023-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_contractvdgo_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='sms',
            field=models.BooleanField(default=False, verbose_name='СМС'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Подтверждение корректности данных'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='is_sended',
            field=models.BooleanField(default=False, verbose_name='Отправлено в реестр'),
        ),
    ]
