# Generated by Django 4.1.7 on 2023-11-19 09:06

import contracts.models
import contracts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contractvdgo_sms_alter_contractvdgo_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='contract_pdf',
            field=models.FileField(blank=True, default='', upload_to=contracts.models.upload_to, verbose_name='Заполненный PDF'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='contract_pdf_signed',
            field=models.FileField(blank=True, default='', upload_to=contracts.models.upload_to, verbose_name='Подписанный PDF'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='account_address',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, validators=[contracts.validators.validate_file_extension], verbose_name='Адрес установки борудования'),
        ),
    ]
