# Generated by Django 4.1.7 on 2023-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contractvdgo_contract_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Получена подпись'),
        ),
    ]
