# Generated by Django 4.1.7 on 2023-11-22 10:13

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_contractvdgo_is_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_first',
            field=models.FileField(blank=True, default='', upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат первый'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_second',
            field=models.FileField(blank=True, default='', upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат второй'),
        ),
    ]
