# Generated by Django 4.1.7 on 2023-11-22 15:17

import contracts.models
import contracts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_contractvdgo_certificate_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='is_izs',
            field=models.BooleanField(default=False, verbose_name='ИЖС'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_fifth',
            field=models.ImageField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат пятый'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_first',
            field=models.FileField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат первый'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_fourth',
            field=models.ImageField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат четвёртый'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_last',
            field=models.ImageField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат шестой'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_second',
            field=models.FileField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат второй'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='certificate_therd',
            field=models.ImageField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='ЕГРН сертификат третий'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='contract_pdf',
            field=models.FileField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='Заполненный PDF'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='contract_pdf_signed',
            field=models.FileField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='Подписанный PDF'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='inn_first',
            field=models.ImageField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='Лицевая сторона ИНН'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_first',
            field=models.ImageField(blank=True, default=None, storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='Второй разворот паспорта'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_scan_second',
            field=models.ImageField(blank=True, default=None, storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='Страница паспорта с регистрацией'),
        ),
        migrations.AlterField(
            model_name='contractvdgo',
            name='snils_first',
            field=models.ImageField(blank=True, default='', storage=contracts.storage.OverwriteStorage(), upload_to=contracts.models.upload_to, verbose_name='Лицевая сторона снилс'),
        ),
    ]
