# Generated by Django 4.1.7 on 2023-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_contractvdgo_is_izs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='error_text',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='contractvdgo',
            name='is_error',
            field=models.BooleanField(default=False, verbose_name='Ошибка'),
        ),
    ]
