# Generated by Django 4.1.7 on 2023-11-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_contractvdgo_error_text_contractvdgo_is_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='passport_serial',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Серия паспорта'),
        ),
    ]
