# Generated by Django 4.1.7 on 2023-11-29 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_contractvdgo_passport_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractvdgo',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
