# Generated by Django 4.1.7 on 2023-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_alter_contractvdgo_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvdgo',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Обработка завершена'),
        ),
    ]
