# Generated by Django 4.1.7 on 2023-04-21 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_number', models.CharField(default='', max_length=8, unique=True, verbose_name='Лицевой счёт (8)')),
                ('account_number_rmg', models.CharField(default='', max_length=12, unique=True, verbose_name='Лицевой счёт (12)')),
            ],
            options={
                'verbose_name': 'Лицевой счёт',
                'verbose_name_plural': 'Лицевые счета',
            },
        ),
    ]
