# Generated by Django 4.1.7 on 2023-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsvalidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsrecord',
            old_name='account_number_rmg',
            new_name='account_number_rng',
        ),
    ]
