# Generated by Django 4.1.7 on 2023-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsvalidate', '0003_alter_lsrecord_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsrecord',
            name='account_number',
            field=models.CharField(default='', max_length=8, unique=True, verbose_name='Лицевой счёт (8)'),
        ),
        migrations.AlterField(
            model_name='lsrecord',
            name='account_number_rng',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='Лицевой счёт (12)'),
        ),
    ]
